import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/Providers/Providers";
import { Toaster } from "react-hot-toast";
import { AuthenticationProvider } from "@/Providers/AuthenticationProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Drone Connect",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/drone-connet.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthenticationProvider>
            <NuqsAdapter>
              <main>{children}</main>
            </NuqsAdapter>
            <Toaster />
          </AuthenticationProvider>
        </Providers>
      </body>
    </html>
  );
}
