import Header from "@/components/header";
import LeftSidebar from "@/components/sidebar-left";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Drone Connect",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/drone-connet.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full">
      <Header />
      <div className="h-full">
        <div className="mx-auto max-w-3xl px-6 lg:grid lg:max-w-full lg:grid-cols-12 lg:gap-8 h-full mt-16">
          {/* left sidebar */}
          <LeftSidebar />
          {/* main content */}
          {children}
        </div>
      </div>
    </div>
  );
}
